# [[redirects]]
#   from = "/api/*"
#   to = "/.netlify/functions/:splat"
#   status = 200

# [[redirects]]
#   from = "/.well-known/*"
#   to = "/.netlify/functions/webfinger"
#   status = 200

# [[redirects]]
#   from = "/api/activitypub/*"
#   to = "/.netlify/functions/:splat"
#   status = 200

# [[redirects]]
#   from = "/users/slay"
#   to = "/.netlify/functions/slay"
#   status = 200

[[headers]]
for = "/user-info/ylay/actor.json"
[headers.values]
Content-Type = "application/activity+json"
